config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :movies do
    collection do
      get 'search'
      get 'recommend'
    end
  end
  resources :posts
  root 'movies#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user! , except: [:show, :search ,:recommend]
  def search
    if params[:looking_for]
      movie_title = params[:looking_for]
      movies = []
      (1..5).each do |page|
        url = "https://api.themoviedb.org/3/search/movie?api_key=#{ENV['TMDB_API']}&language=ja&query=" + URI.encode_www_form_component(movie_title) + "&page=#{page}"
        response = Net::HTTP.get_response(URI.parse(url))
        if response.code == "200"
          result = JSON.parse(response.body)
          movies.concat(result["results"])
        end
      end
    else
      movies = []
      (1..4).each do |page|
        url = "https://api.themoviedb.org/3/movie/popular?api_key=#{ENV['TMDB_API']}&language=ja&page=#{page}"
        response = Net::HTTP.get_response(URI.parse(url))
        if response.code == "200"
          result = JSON.parse(response.body)
          movies.concat(result["results"])
        end
      end
    end
    @movies = Kaminari.paginate_array(movies).page(params[:page]).per(16)
  end

  def show
    movie_id = params[:id]
    url = "https://api.themoviedb.org/3/movie/#{movie_id}?api_key=#{ENV['TMDB_API']}&language=ja"
    response = Net::HTTP.get_response(URI.parse(url))
    if response.code == "200"
      @movie = JSON.parse(response.body)
      if @movie["overview"].blank?
        url_en = "https://api.themoviedb.org/3/movie/#{movie_id}?api_key=#{ENV['TMDB_API']}&language=en"
        response_en = Net::HTTP.get_response(URI.parse(url_en))
        if response_en.code == "200"
          movie_en = JSON.parse(response_en.body)
          @movie["overview"] = movie_en["overview"]
        end
      end
    else
      @movie = nil
    end
  end

  def recommend
    if params[:query].present?
      client = OpenAI::Client.new(access_token: ENV["OPENAI_API_KEY"])
      response = client.chat(
        parameters: {
          model: "gpt-3.5-turbo",
          messages: [{  role: "user", 
                        content: "次のキーワードに該当する映画を`タイトル:公開年,監督`順番で10作品教えてください。また各作品情報の最後に '\n'を入れて下さい。keyword:#{params[:query]}"
                    }],
        })
  
      @answer = response.dig("choices", 0, "message", "content")
    end
  end
  
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/recommend.html.erb
<div class="recommend-container">
  <div class="question">
    <%= form_with(url: recommend_movies_path, method: :get) do |form| %>
      <%= form.text_field :query, size: 50, placeholder: "知りたい映画のテーマ、キーワード" %>
      <%= form.submit "質問する", class: "postbtn" %>
    <% end %>
  </div>
<hr>
  <div class="answer">
    <% if @answer %>
      <%= h(@answer).gsub(/\n|\r|\r\n/, "<br>").html_safe %>
    <% else %>
      <h3>※現在OpenAI APIキーの利用費削減により使用不可です🙇‍♂️</h3>
      <%# <p>質問してね！！！</p>
      <p>※返答に30秒程かかります！気長にお待ちください！</p> %>
    <% end %>
  </div>
</div>
<br>
<hr>

app/views/movies/search.html.erb
<div class="search">
    <%= form_tag(root_path, method: :get) do %>
        <%= search_field_tag :looking_for, nil, placeholder: 'Movie Title...' , :size => "40*40" %>
    <% end %>
</div>
<%= paginate @movies %>
<div class = "movies-container">
    <% @movies.each do |movie| %>
        <div class = "movie-data">
            <p class= "movie-title"><%= movie['title'] %></p>
            <%= link_to movie_path(movie['id']) do %>
                <% if movie['poster_path'] %>
                    <p><%= image_tag 'https://image.tmdb.org/t/p/w200' + movie['poster_path'],class: "card-img" %></p>
                <% end %>
            <% end %>
        </div>
    <% end %>
</div>
<%= paginate @movies %>

app/views/movies/show.html.erb
<div class="movie-detail">
  <div class="movie-info-with-image">
    <% if @movie['poster_path'] %>
      <%= image_tag 'https://image.tmdb.org/t/p/w200' + @movie['poster_path'], class: "card-size" %>
    <% end %>
    <div class="movie-info">
      <div class="movie-header">
        <h1><%= @movie['title'] %></h1>
        <p><%= @movie['runtime'] %> 分</p>
        <p><%= @movie['release_date'] %> 公開</p>
      </div>
      <div class="movie-overview">
        <p><%= @movie['overview'] %></p>
      </div>
    </div>
  </div>
  <%= link_to "この映画をメモる", new_post_path(movie_id: @movie['id']), class:'postbtn' %>
</div>